default : 
  base_exception : '[red]UnknownException[/] : [blue]Unknown Exception Occured[/]\n [green]{params}[/]'

config :
  invalid_config : '[red]InvalidConfig[/] : [green]Config For [yellow]{source}[/] Missing Required Fields [yellow]{missing_fields}[/][/]'

logger : {
        
}
validator : {
        
}
exception_handler : {
        
}
other : {
        
}